### ISSUE TITLE
What sort of licensing would be required to share this reports

### ISSUE THREAD

**Issue by artisticcheese** [chris-bowman/Azure-Cost-Reporting#10]
Please add documentation about licensing requirements for creating and consuming this report.

**Comment by chris-bowman** [comment]
Hi @artisticcheese, you will require the same licensing you would to publish/share in PowerBI (generally a Power BI Pro or Premium Per User license). I have added a link in the readme to the PowerBI documentation. You won't need additional licesnes for Azure to connect to the ACM data, just the required Azure RBAC access.

See [Ways to collaborate and share in Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports) for details
