### ISSUE TITLE
Add Currency EUR in dashboards

### ISSUE THREAD

**Issue by VisFGO** [chris-bowman/Azure-Cost-Reporting#22]
Hello 
can you add EUR currency in dashs?
thanks

**Comment by chris-bowman** [comment]
Hi @VisFGO The report just shows the billing currency fields, so if your billing currency is EUR then the values should be in Euros (the data comes from CostInBillingCurrency field, just renamed Cost for simplicity) - you can change the format to show the Euro symbol (Power BI defaults to $):
![screenshot of currency symbol dropdown in Power BI](https://github.com/chris-bowman/Azure-Cost-Reporting/assets/20289947/4d943e4d-c77a-48c5-80f4-766e27e1ba2f)

**Comment by VisFGO** [comment]
thks it's ok 
cdt

**Comment by RandomUsernameThatIsNotYetTaken** [comment]
@chris-bowman  sorry for resurrecting this thread;
Im in the same boat;
So far ive reconfigured  a few fields to Euro given that the table had a currency field set to EUR also.

Am i correct in understanding that for the RI Recommendations view all values are USD from the source?
Should I use currency conversion similar to the usage details table?

![image](https://github.com/chris-bowman/Azure-Cost-Reporting/assets/45180330/3a46f6b0-8920-4273-ac8b-e066e83ed508)
