### ISSUE TITLE
Error refresh last this two days  ( in MCA contexte)

### ISSUE THREAD

**Issue by VisFGO** [chris-bowman/Azure-Cost-Reporting#25]
hello 
i have this error since sunday :
 The column '[ccon]InstanceId[/ccon]' of the table wasn't found.. [ccon]InstanceId[/ccon]. [/ccon]. The exception was raised by the IDbCommand interface. Table: RI Usage.
"sorry, we couldn't find the "InstanceId" column in the table. We couldn't find the "InstanceId" column in the table."
Have you any idea ?
thks

**Comment by chris-bowman** [comment]
Yes, I have noticed this as well. This appears it may be an underlying issue with the Cost Management connector for the riusagedetails table, as there's no reference to InstanceId in the table. This may be a transient issue with the underlying API the connector uses. I'd suggest logging a support case from your Azure Portal to get it investigated.

![image](https://github.com/chris-bowman/Azure-Cost-Reporting/assets/20289947/11fbd373-2a42-4091-93ea-28f3137afd4e)

**Comment by VisFGO** [comment]
Hello this is a general issue ...
https://community.fabric.microsoft.com/t5/Developer/Azure-Cost-Management-RI-Usage-Details-Column-InstanceId-Not/m-p/3756367/highlight/false#M50326
I logged a ticket 
thnks

**Comment by chris-bowman** [comment]
Hi @VisFGO. This appears to have been resolved now, the RIUsage table is loading properly for me. Let me know if you're still having issues.

**Comment by VisFGO** [comment]
Hi Chris
Yes it's ok
Thks


***@***.***<https://cloud.letsignit.com/collect/bc/623dd7efe20bc418ee2bf26f?p=XAPIHFmM0jVYF0oeu-OsurFUvWJxJiNV26-_18FHyBPjtMtkpmGTIMcpvF9GeWxCf3W20onVrA5PZVfsbRWW97GqXcXWP1mXkvC1B8y0xQDbMNIpoQOXVuN-CfWwGxnsCXXM_LHLESvJ6ZAEjAXv_lZOUboq09D_mQHdeOU7vRk=>

Fabien GOUINEAU

Architecte

0784264876





De : Chris Bowman ***@***.***>
Envoyé : lundi 18 mars 2024 03:30
À : chris-bowman/Azure-Cost-Reporting ***@***.***>
Cc : Fabien GOUINEAU ***@***.***>; Mention ***@***.***>
Objet : Re: [chris-bowman/Azure-Cost-Reporting] Error refresh last this two days ( in MCA contexte) (Issue #25)

Vous ne recevez pas souvent de courriers de la part de ***@***.******@***.***>. Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Hi @VisFGO<https://github.com/VisFGO>. This appears to have been resolved now, the RIUsage table is loading properly for me. Let me know if you're still having issues.

-
