### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by savenpa** [chris-bowman/Azure-Cost-Reporting#3]
Hi Chris,

Your doco refers to Enterprise Admin/Reader role but this is now known as Global Admin/Reader roles.

Also does the Azure Plan have any impact on reporting?  I could not see how it linked into the model.

Paul

**Comment by chris-bowman** [comment]
Hi Paul,

Within the Azure enterprise agreement (EA) the administrative roles are still called Enterprise Admin and Admin (read-only) ([https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/ea-direct-portal-get-started#understanding-ea-user-roles-and-introduction-to-user-hierarchy](doc link)). When MCA is available, I'll update this section with the Billing Profile roles as well.

Regarding the plan parameter, it affects the lookups for estimating Windows license cost in the AHBUsage table - it's on my to-do list to remove in a future release to use the row-level data for individual subscription types. This first release was actually a conversion from the EA API key-based Consumption Insights connector to use the ACM connector, so still has some leftovers not yet cleaned up :)

**Comment by savenpa** [comment]
Hi Chris,

The portal http://ea.azure.com is deprecated now (at least from what I see) and the Doco on learn.microsoft.com looks like it is out of date to as everything redirects you to portal.azure.com.  Hopefully that will all catch up as ea.portal.com fades away.

![image](https://user-images.githubusercontent.com/68044862/225451168-74864046-e026-4b08-bb6c-4f89ef1cc27d.png)
