### ISSUE TITLE
Using the reporting dashboard with MCA accounts

### ISSUE THREAD

**Issue by Speedway-Stadium** [chris-bowman/Azure-Cost-Reporting#4]
Hello Chris, could this reporting dashboard be used with non EA (i.e. MCA subscriptions) Azure accounts? It fails to load any of the data when I attempt to connect to our account.

Thank you

**Comment by chris-bowman** [comment]
The MCA data model is slightly different to the EA one, and I am working on this for a future release as I now have access to an MCA billing profile. 

Stay tuned

**Comment by khurrambilalaurecon** [comment]
Waiting for MCA version, fingers crossed!

**Comment by chris-bowman** [comment]
Closing as resolved by v3.1
