### ISSUE TITLE
Utilisation Calculation for RIs

### ISSUE THREAD

**Issue by savenpa** [chris-bowman/Azure-Cost-Reporting#5]
Hi Chris,

Doing a bit of work around RI utilisation.  I noted in RI  Usage and RI Usage Summary you are taking the AVG (Used/Reserved) Hours.  In the data how ever this does not work as the used hours can be spread across multiple resources/subscriptions.

Utilisation = AVERAGEX('RI Usage Summary','RI Usage Summary'[UsedHours]/'RI Usage Summary'[ReservedHours])

I think the correct usage is SUM(Used)/AVG(Reserved) hours.

Uilisation2 = SUMX('RI Usage Summary','RI Usage Summary'[UsedHours])/AVERAGEX('RI Usage Summary','RI Usage Summary'[ReservedHours])

Can you check/confirm and if needed update PBI?

Paul

**Comment by chris-bowman** [comment]
The RI utilisation metric I have not reviewed for 3 years since the old EA API connecter. Will investigate in the next update.

**Comment by chris-bowman** [comment]
Hi @savenpa,

I've reviewed the calculations and the 'RI Usage' table already takes into account where the RI was eventually used (the 'name' column refers to the resourceId which consumed it), so it already does take that into account. I did find however there was a problem with Instance Size Flexibility (when the ratio is in use, it will multiply the used/reserved hours to suit, however this was skewing the utilisation %). After accounting for normalising the hours back to ratio=1, the average formula still holds true - note that in 'RI Usage Summary' I am aggregating _per day_. 

This will be included in the next release, which I hope to publish soon.

An example for a single day for a 2x E64ds_v4 reservation, so you have 48 hours per day. In the RI Usage tables you see the following:
![screenshot of Reservation Data](https://user-images.githubusercontent.com/20289947/228089624-8e7671fc-e60f-42c2-b2ab-8ccb7e702f42.png)

You can see the problem with ISF here, which I have now normalised in the RI Usage Summary table.

**Comment by chris-bowman** [comment]
Closing as resolved by v3.1
