### ISSUE TITLE
RI Transactions - The column 'id' of the table wasn't found.

### ISSUE THREAD

**Issue by ChiefChronoX** [chris-bowman/Azure-Cost-Reporting#6]
When trying to use your report template and filling out the information, the report is trying to refresh the tables and I get below error which is blocking all other tables from being refreshed.

Could it be because I'm not 100% sure if I'm using the correct DefaultOfferId? I assume it's the subscription ID?

![thumbnail_image001](https://user-images.githubusercontent.com/961772/227859040-01da652b-00ba-4e5e-8077-c92f94d4222f.png)

**Comment by chris-bowman** [comment]
Strange, I have not seen this error, although have only been able to test with an Enterprise Enrollment (with and without any Reservation transactions). Are you using an Enterprise Enrollment or Billing Account (MCA)? MCA is not yet supported, but will be in a new release soon. DefaultOfferId will also be removed.

**Comment by mborgers** [comment]
I've encountered  the same problem. I'm using the Enterprise Enrollment ID. The query can't find the id at reordered columns:
<img width="1054" alt="ID Error" src="https://user-images.githubusercontent.com/29546736/228156073-af4e32eb-6d74-4e76-9a4e-c0ea54a21192.png">
I removed 'Reorderd Columns' and 'Removed Columns' and now the report seems to be working. However I have no idea on the impact that this will have.

**Comment by ChiefChronoX** [comment]
The issue seems to be gone with the new 3.1 version, it’s working just fine now. I’m using Enterprise Enrollment by the way. Thanks for publishing this new version so quickly.

Sent from my iPhone

On 28 Mar 2023, at 00:34, Chris Bowman ***@***.***> wrote:

﻿

Strange, I have not seen this error, although have only been able to test with an Enterprise Enrollment (with and without any Reservation transactions). Are you using an Enterprise Enrollment or Billing Account (MCA)? MCA is not yet supported, but will be in a new release soon. DefaultOfferId will also be removed.

**Comment by chris-bowman** [comment]
Ah glad to hear it has resolved with 3.1 - I actually removed the reorder columns step. I did notice that if no reservations have been purchased, then the 'id' column disappears from the dataset, which may account for it.

Resolved by #7
