### ISSUE TITLE
30 Days Ammortized doesn't match monthly Bill

### ISSUE THREAD

**Issue by sofbkeller** [chris-bowman/Azure-Cost-Reporting#9]
Hi Chris,

We were testing out this PBI tool but ran into issues where the data shown in the 30 Days Ammortized and the Cost by Month values were different than the amounts shown on our Azure bill. The amount in PBI was about $10K higher than what was on our bill and we were not able to reconcile the differences. 
What troubleshooting/testing could we do to compare those values to try and match them up better?

**Comment by chris-bowman** [comment]
The 30 days Amortized visual is based off the past 30 calendar days, which may not have all the billing data in the system yet (so it's not necessarily a great measure, depends on when you refresh the data and how stale it is in ACM - it could have only 28 or 29 days of data). Are the actual month to month figures correct in the Summary tab graphs? Note also the report (generally) uses the Amortized cost values, so if comparing in ACM make sure you [switch to show Amortized Costs there](https://learn.microsoft.com/en-us/azure/cost-management-billing/reservations/charge-back-usage#see-reservation-usage-data-for-show-back-and-charge-back)

**Comment by chris-bowman** [comment]
Closing this issue - please reopen if you have any futher concerns. If the numbers don't match between what you see in Azure Cost Management (Amortized view) vs the PowerBI report it may be worth raising a support case to investigate as these should line up.
